site_name: Rezepte
site_url: https://achimgrolimund.github.io/meine_rezepte/
site_author: Achim Grolimund
theme:
  name: material
  locale: de

extra_javascript:
  - custom_theme/js/extra.js
extra_css:
  - custom_theme/css/extra.css
